[package]
name = "doodlebob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
bevy_sprite = "0.9.1"
bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls"}

[profile.dev.package."*"]
opt-level = 3


